# Ответы игроков
docType = "UserAnser"

tableName ="user_answer"

fields = [
    {name="id",                 type="serial"},
    {name="user_id",            type="int",         ext="not null"},
    {name="survey_qstn_id",     type="int"},
    {name="score",              type="double",      ext="DEFAULT 0"},
    {name="is_right",           type="bool"},
    {name="user_answer",        type="text"},
    {name="true_answer_list",   type="text[]"},
    {name="details",            type="jsonb"},
    {name="created_at",         type="timestamp",   ext="without time zone"},
    {name="deleted",            type="bool",        ext="not null default false"}
]

fkConstraints = [
    {fld="user_id", ref="\"user\"", fk="id"},
    {fld="survey_qstn_id", ref="survey_qstn", fk="id"},
    # ограничение, что должна быть ссылка либо на игру, либо на вопрос из опросника
#    {name="need_link_to_survey_or_game", ext="CHECK (tg_game_id IS NOT NULL OR survey_qstn_id IS NOT NULL)"},
    # ограничение, чтобы ответ игрока на конкретный вопрос был только один
    {name="for_user_answer_on_this_qstn_already_exist", ext="UNIQUE (user_id, survey_qstn_id)"}
]

methods = [
    "user_answer_list"
]