# Связь пользователь - место работы, по которому у него есть полномочия прводить авторизацию
docType = "LinkAuthBusinessPlaceUser"

tableName ="link_auth_business_place_user"

fields = [
    {name="id",          type="serial"},
    {name="user_id",     type="int",        ext="not null"},
    {name="place_id",    type="int",        ext="not null"},
    {name="deleted",     type="bool",       ext="not null default false"},
    {name="",            type="constraint", ext="UNIQUE (user_id, place_id)"}
]

fkConstraints = [
    {fld="user_id", ref="\"user\"", fk="id"},
    {fld="place_id", ref="business_position", fk="id"}
]
